export const team = [
    {
        id: 1,
        name: 'Paweł',
        surname: 'Jadach',
        nick: 'Bad Boy',
        role: 'CEO',
        img: '/team/200x300/pawel.png',
        type: 'stuff',
    },
    {
        id: 2,
        name: 'Mateusz',
        surname: 'Pędlowski',
        nick: 'Dartizer',
        role: 'Social media',
        img: '/team/200x300/mateusz.png',
        type: 'stuff',
    },
    {
        id: 3,
        name: 'Dawid',
        surname: 'Nabożny',
        nick: 'Kocur',
        role: 'Sim Racing',
        img: '/team/200x300/kocur-czapka.png',
        type: 'simRacing',
    },
    {
        id: 4,
        name: 'Jan',
        surname: 'Garbas',
        nick: 'Denan',
        role: 'Sim Racing',
        img: '/team/200x300/garbas-medal.png',
        type: 'simRacing',
    },
    {
        id: 5,
        name: 'Mateusz',
        surname: 'Kędzia',
        nick: 'KD',
        role: 'Sim Racing',
        img: '/team/200x300/kedzia.png',
        type: 'simRacing',
    },
    {
        id: 6,
        name: 'Tomek',
        surname: 'Kubiak',
        nick: 'Kemot',
        role: 'Sim Racing',
        img: '/team/200x300/kemot.png',
        type: 'simRacing',
    },
    {
        id: 7,
        name: 'Mateusz',
        surname: 'Grzonka',
        nick: 'MATTY',
        role: 'Sim Racing',
        img: '/team/200x300/grzonka.png',
        type: 'simRacing',
    },
    {
        id: 8,
        name: 'Mateusz',
        surname: 'Peczka',
        role: 'Sim Racing',
        img: '/team/200x300/peczka.png',
        type: 'simRacing',
    },
];